sparkbox/accessible-components

package-lock.json
src/pages/index.js
src/styles/globals.scss

Set up listing page
See Story: [FSA22V2-217](https://sparkbox.atlassian.net/browse/FSA22V2-217?atlOrigin=eyJpIjoiZmYzNmM2ZWUzMzcwNGFiNGFiYmZmN2U4MDUzMjIxZTIiLCJwIjoiaiJ9)
- removed any boilerplate css and html
- updated homepage content per project details
3. Navigate to localhost:3000, check page(s) for Pr.
4. In terminal: npm run lint.
Ensure that you only see "“Accessibility Cheatsheets for Components”, and an unordered list of links to the four components on localhost: 3000, no remaining boilerplate html on index page or stray boilerplate css files.
---
In these browsers, behavior & design closely match original specifications. A user …

Fsa22 v2 217 setup listing page

---

.github/pull_request_template.md

Add validation information to PR Template
See Story: relates to update on - [FSA22V2-215](https://sparkbox.atlassian.net/browse/FSA22V2-215?atlOrigin=eyJpIjoiZjY1OWE4NjYwNzgwNGQzNTgzMTk1MzZlMTBiMjBiM2QiLCJwIjoiaiJ9)
improve validation instructions, specify accessibility testing as this is an accessibility-related site!
3. In terminal: `npm run dev.`
4. Check [localhost: 3000](http://localhost:3000/) for changes.
6. Run axe DevTools on affected pages.
7. Confirm all tests pass.
---
In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, …

feat: add validation information PR template

---

src/pages/[id].js

Set up component details page.
See Story: [FSA22V2-218](https://sparkbox.atlassian.net/browse/FSA22V2-218?atlOrigin=eyJpIjoiZmRkYWIxMTgzNGExNDM1ZmIxZjk0NTZkMjk3ZGI1YTEiLCJwIjoiaiJ9)
4. Check [localhost: 3000](http://localhost:3000/) for changes.
6. Run axe DevTools on affected pages.
7. Confirm all tests pass.
Check that dynamic route page where details function returns an id dynamically based on the router query in an h1 tag.
---
In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, including the usability of …

feat: set dynamic routes

---

src/pages/404.jsx

Setup: 404 Page
See Story: [FSA22V2-214](https://sparkbox.atlassian.net/browse/FSA22V2-214?atlOrigin=eyJpIjoiNGY4YzFiYzc0OGVjNDQzNGJmYWYyZTZiNTcwZWY4ZjEiLCJwIjoiaiJ9)
4. Check [localhost: 3000](http://localhost:3000/) for changes.
6. Run axe DevTools on affected pages.
7. Confirm all tests pass.
Check that dynamic route page where details function returns an id dynamically based on the router query in an h1 tag.
---
In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, including the usability of required …

feat: add 404 page

---

.eslintrc.json
.github/workflows/main.yml
src/pages/404.jsx
src/pages/[id].js
src/pages/index.jsx
src/pages/index.test.js
src/styles/components/index.scss

Sets up github actions for testing `npm run lint` and `npm run test`.
See Story: [FSA22V2-212](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-212)

Added main.yml file

---

.github/workflows/main.yml
src/pages/index.jsx
src/styles/components/_home.scss

Github action will check if the commit messages are formatted correctly.
See Story: [FSA22V2-231](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-231)
2. Commit Message CI check below should not be failing because it has a proper commit title.

CI check for commit formatting

---

.github/pull_request_template.md
README.md

FSA22V2-230
Added pre-commit hook instructions to template.
See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-ISSUE)
4. Check [localhost:3000](http://localhost:3000/)for changes.
6. Run axe Devtools on affected pages.
7. Confirm all tests pass.
Please check that pre-commit hook has been included in the instructions on the template (should now be step #6 in the commit).
In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, including the usability of required assistive devices, such as …

feat: add precommit hook instructions

---

src/components/SpecificationBlock.jsx
src/components/SpecificationBlock.test.jsx
src/pages/[id].page.jsx
src/styles/components/_specificationBlock.scss
src/styles/globals.scss

This component will display a block of data representing Focus Expectations, Keyboard Interactions, Semantic Elements, and ARIA Roles and Attributes.
Designs: [Figma](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A663)
See Story: [FSA22V2-259](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-259)
4. Run `npm run lint`.
5. Run axe Devtools on affected pages.
6. Confirm all tests pass.
7. Go to [localhost:3000](http://localhost:3000/accordion) to see the details page, for the accordion component. You should see the 8. specification block …

Component: Specification Block

---

src/components/ComponentCard.jsx
src/pages/index.test.jsx
src/styles/components/_component-card.scss

After a misunderstanding, I realized I had no anchor tags for the component cards. This PR adds them back in so our components are keyboard accessible once more. 
See Story: Fixed with no story
4. Check [localhost:3000](http://localhost:3000/) for changes.
5. Start on the homepage. Using only the keyboard, tab/navigate to any component card. Enter the individual component details pages by pressing `return`. 
6. Run `npm run lint` to confirm no errors. 
7. Run `npm run test` to confirm all tests pass.
---
In these browsers, behavior & design closely match original specifications. A user is able to access all content and functionality, …

FSA22V2-000: Fix Missing anchor tags

---

src/components/SpecificationBlock.jsx
src/pages/[id].page.jsx
src/styles/components/_specification-block.scss
src/styles/globals.scss

The specifications section for each component has been refactored into a new grid layout for larger screen sizes. Our grid consists of 2 columns, with some elements spanning 1 column, and others spanning both columns. 
Note: The upcoming Rich Text component will handle the content for individual sections, so the main concern here is the grid layout. (We will return to the two-column layout of the ARIA Roles & Attributes specifically once we having integrated our real data) 
Designs: [Figma Designs](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A663)
More specifically:  
See Story: [FSA22V2-243](https://sparkbox.atlassian.net/browse/FSA22V2-243)
2. Pull down all …

FSA22V2-243: Component Specifications Section

---

.github/pull_request_template.md
README.md

Recently, the Airtable integration was merged, which means that all developers (both contributors and reviewers) will need to have their local environments set up to accommodate Airtable. Instructions on how to add the proper environment variables were added in the PR template and README. Additionally, a section for "Pending Questions" was added to the PR at the suggestion of other full-time devs to put questions still remaining about the PR/code/future functionality.
See Story: [FSA22V2-267](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-267)
The goal is for you to get into one of the component details page with no server errors about Airtable. 
The updated validation steps are: 
1. Make sure all PR Checks have passed (GitHub …

FSA22V2-267: Documentation update for environment variables

---

package-lock.json
src/pages/index.page.jsx
src/pages/index.test.jsx
src/styles/components/_component-card.scss
src/styles/components/_component-grid.scss
src/styles/components/_footer.scss
src/styles/components/_header.scss
src/styles/components/_home.scss
src/styles/elements/_ul.scss
src/styles/globals.scss
src/styles/tools/_mixins.scss

From mobile to desktop, the homepage/listing page should now match the Figma designs. Fonts, sizes, weights, borders, focus states, missing headings, padding, margins, max-width for extra-large screens, image behavior all should be fixed. 
This PR is limited to the homepage styles only (mobile/light-mode). 
Designs: [Designs](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A663)
See Story: [FSA22V2-277](https://sparkbox.atlassian.net/browse/FSA22V2-277)
4. Copy the `.env.example` file, making sure it's in the root of your project, …

FSA22-V2 277: Fix Up Listing Page styles

---

src/pages/[id].page.jsx
src/styles/components/_specification-block.scss

Usage guidelines was accidentally duplicated during a rebase or merge, so it is removed now from the `details` object it was being stored in. Additionally, because the rest of the Airtable data is now being populated, the specification grid was adjusted (mainly to match Airtable data with `grid-template-area` names. 
FSA22V2-272
You can see Usage Guidelines in the proper teal section, and then incorrectly in the specification grid below: 
Bug Card: [FSA22V2-281](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-281)
3. Run `npm install` to make sure you have all proper dependencies. (this project requires Node …

Fix: Specification grid duplicates

---

src/components/CodeBlock.jsx
src/components/CodeBlock.test.jsx
src/pages/[id].page.jsx
src/styles/components/_code-block.scss
src/styles/globals.scss

The code example has been added! 
Designs: [Designs](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A663)
See Story: [FSA22V2-272](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-272)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created `.env.local` file. That should establish your connection …

FSA22-V2 272: Code Block Component 

---

src/code-examples/accordion/css.js
src/code-examples/accordion/html.js
src/code-examples/accordion/javascript.js
src/code-examples/dialog/css.js
src/code-examples/dialog/html.js
src/code-examples/dialog/javascript.js
src/code-examples/disclosure/css.js
src/code-examples/disclosure/html.js
src/code-examples/disclosure/javascript.js
src/code-examples/tabs/css.js
src/code-examples/tabs/html.js
src/code-examples/tabs/javascript.js
src/components/CodeBlock.jsx
src/pages/[id].page.jsx
src/styles/components/_code-block.scss

FSA22V2-30
- add folders for dynamic imports of code snippets.
- add useState and useEffect hooks to import slug based on required code
javascript file.
- add code blocks specifically bringing in test code for html, javascript,
and css code example snippets.
See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-283?atlOrigin=eyJpIjoiOGRhZDJmZDdiYjhiNDZmMGI1NzZmMWQ2NjIyMjcyZTQiLCJwIjoiaiJ9)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible …

feat: add folders for dynamic imports

---

src/code-examples/disclosure/css.js
src/code-examples/disclosure/html.js
src/code-examples/disclosure/javascript.js

FSA22V2-275
- add html, css, and javascript code for disclosure component code example.
Designs: [Designs](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone)
See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-275?atlOrigin=eyJpIjoiYzNjYTU3MDY0ZWI0NGYxN2E5ODhiM2M2MWZhYTYzMmMiLCJwIjoiaiJ9)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created …

feat: add integration for disclosure component

---

src/pages/index.page.jsx
src/styles/components/_home.scss

We scrapped this date section, so it's removed from the homepage. 
See Story: [FSA22V2-289](https://sparkbox.atlassian.net/browse/FSA22V2-289)
5. Run `npm run lint` to confirm no errors.
6. Run `npm run test` to confirm all tests pass.
7. In terminal: `npm …

FSA22V2-289: Refactor: remove mm/dd/yyyy

---

src/components/RichText.jsx
src/components/RichText.test.jsx
src/styles/elements/_kbd.scss
src/styles/globals.scss

Targeting the `[[` and `]]`, I replaced the visually-cluttered double brackets with the `<kbd>` elements. 
From this: 
To this: 
See Story: [FSA22V2-282](https://sparkbox.atlassian.net/browse/FSA22V2-282)
5. Run `npm run lint` to confirm no errors.
6. Run …

FSA22V2-282: Integration: replace double brackets in rich text with kbd tags

---

src/code-examples/dialog/css.js
src/code-examples/dialog/html.js
src/code-examples/dialog/javascript.js

After getting WAS approval, the dialog code was imported into the 3 corresponding languages in the Dialog folder. 3 code example blocks are generated with the dialog code.
CodePen: [Dialog Example](https://codepen.io/mhuysentruyt/pen/ZERKpBJ?editors=0011)
See Story: [FSA22V2-274](https://sparkbox.atlassian.net/browse/FSA22V2-274)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created …

FSA22V2-274: Feat: Dialog code example integration

---

src/code-examples/accordion/css.js
src/code-examples/accordion/html.js
src/code-examples/accordion/javascript.js
src/styles/components/_details-page.scss

- Add HTML, CSS and JS for the WCAG-compliant accordion component example
The accordion being added in this PR is meant to serve as a bare-bones template for developers. It should meet the WCAG guidelines described for the accordion design pattern and have simple, understandable javascript controlling it. The styling is intentionally minimal so that it can be easily expanded upon and customized for any project.
CodePen: [Accordion](https://codepen.io/jared-kohrt/pen/bGKRxQV)
See Story: [FSA22V2-273](https://sparkbox.atlassian.net/browse/FSA22V2-273)
2. Pull down `FSA22V2-273-integration-accordion-code-example`.
3. Run `npm install` to make sure you have all proper dependencies. (this project requires …

FSA22V2-273: Accordion code example

---

src/pages/index.page.jsx

FSA22V2-288
Change placeholder text to actual intro text on home page.
Designs: [Designs](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=244%3A2183&t=A0sL00y3exNBMMfW-0)
See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-288?atlOrigin=eyJpIjoiNmU5YTRlNGU5NzVkNDlmNzllOTNhMzAzNTI0YWMyZWQiLCJwIjoiaiJ9)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to …

feat: replace home page text

---

package-lock.json
package.json
src/pages/[id].page.jsx
src/styles/components/_sandpack.scss
src/styles/generics/_root.scss
src/styles/globals.scss

DISCLAIMER! Pa11y is causing the build to fail on each component details page with this error: ` Error: Evaluation failed: Error: allowedOrigins value "null" is not a valid origin`. We can ignore those pa11y errors for now, because this branch is being merged into a "temporary" sandpack branch and NOT into `main`. We're refactoring, and re-approaching our automated accessibility checks to use Cypress instead of pa11y (which we hope will resolve the current errors/failures). 
Instead of hard-coded component example code, this PR shows Sandpack as a viable live code editor for them instaed. Sandpack accepts HTML, CSS, and JavaScript code for each component. 
From this: 
To this: 
See Story: [FSA22V2-300](https://sparkbox.atlassian.net/browse/FSA22V2-300)
1. Make sure all PR Checks have …

FSA22V2-300: Feat: Sandpack examples

---

src/code-examples/accordion/css.js
src/code-examples/accordion/html.js
src/code-examples/accordion/javascript.js
src/code-examples/dialog/html.js
src/code-examples/dialog/javascript.js
src/code-examples/disclosure/html.js
src/code-examples/tabs/css.js
src/code-examples/tabs/html.js
src/code-examples/tabs/javascript.js

After finding an extra `role="button` on a button element, we did an overview of the built components to ensure that there were no other redundancies found in the markup. We found an additional, duplicated type attribute in one of the components, and removed some unnecessary default attributes that did not change the functionality or accessibility of the components. 
Additionally, some visual code clean up was done to remove unnecessary whitespace/lines and fix indentations for certain lines now  the files get utilized by Sandpack.
See Story: [FSA22V2-317](https://sparkbox.atlassian.net/browse/FSA22V2-317)
3. Run `npm install` to make sure you have all proper …

FSA22V2-317: Fix: Code Examples use accessible markup

---

src/pages/[id].page.jsx
src/styles/components/_definition.scss

Add a try/catch block to ensure that even if the code examples are missing or didn't load, the page just loads without the Sandpack example.
See Story: [FSA22V2-322](https://sparkbox.atlassian.net/browse/FSA22V2-322)
5. Run `npm run lint` to confirm no …

FSA22V2-322: Feat: Add Error Handling for code examples
