sparkbox/accessible-components

.github/dependabot.yml

Add dependabot.yml file to check for weekly npm updates to dependencies. This file is in the `.github` folder, named `dependabot.yml`. 
See Story: [FSA22V2-216](https://sparkbox.atlassian.net/browse/FSA22V2-216)
3. Confirm `dependabot.yml` file: 
a. is valid
b. is named correctly
c. lives in the correct place in this repo
---
1. As Quinn mentioned in a comment, should we add an `open-pull-request-limit` to the dependabot file at all? What would the limit be? 
2. Similarly, should we be more specific about the schedule (day and/or time) that the update checks run? Is there a better or worse day? 
3. Since Sparkbox has specific branch naming strategies, should we utilize …

FSA22V2-216: Add support for dependabot

---

package-lock.json
package.json

In order to make development for consistent, all devs are now forced to be on a version of node 16 or higher.
See Story: [FSA22V2-229](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-229)
3. Switch to node version under 16.
4. In terminal: `npm run dev`. Should get an error.
5. Switch to a node version 16 or higher.
6. In terminal: `npm run dev`. Should run normally.

Added required node version

---

jest.setup.js
package-lock.json
package.json
src/components/Definition.test.jsx
src/components/DetailsBanner.test.jsx
src/components/Footer.test.jsx
src/components/Layout.test.jsx
src/components/RichText.jsx
src/components/RichText.test.jsx
src/components/SpecificationBlock.test.jsx
src/pages/[id].page.jsx

- Add RichText.jsx, a component that creates clean HTML from markdown
- Add tests for RichText.jsx to ensure the most important parts of parsing and cleaning are functional.
Designs: [Main use of RichText](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=69%3A400)
See Story: [FSA22V2-239](https://sparkbox.atlassian.net/browse/FSA22V2-239)
3. In terminal, run `npm i` to install new dependencies and then `npm run dev` to run the web app.
4. Check [localhost:3000](http://localhost:3000/accordion) to make sure header four subheaders with "lorem ipsum" filler appear.
6. Confirm all tests pass.

Fsa22 v2 239 component rich text renderer

---

package-lock.json
package.json
src/components/ComponentCard.jsx
src/components/Header.jsx
src/pages/404.page.jsx
src/styles/components/_definition.scss

This PR should update NextJs and `eslint-config-next` to version 13. In Next13 we don't need to have `<a>` tags inside Links anymore, so we can remove them.
See Story: [FSA22V2-279](https://sparkbox.atlassian.net/jira/software/c/projects/FSA22V2/boards/125?modal=detail&selectedIssue=FSA22V2-279)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created `.env.local` file. That should establish …

FSA22V2-279: Update to Next13

---

src/styles/components/_code-block.scss
src/styles/components/_component-card.scss
src/styles/components/_component-grid.scss
src/styles/components/_definition.scss
src/styles/components/_detailsBanner.scss
src/styles/components/_footer.scss
src/styles/components/_header.scss
src/styles/components/_home.scss
src/styles/components/_related-components.scss
src/styles/components/_specification-block.scss
src/styles/components/_usage-guidelines.scss
src/styles/globals.scss
src/styles/settings/_breakpoints.scss

Sass breakpoint variables are updated throughout the code base to use descriptive names rather than device-type names.
See Story: [FSA22V2-284](https://sparkbox.atlassian.net/browse/FSA22V2-284)
5. Run `npm run lint` to confirm …

Fsa22 v2 284 refactor rename breakpoint sass variables

---

src/pages/[id].page.jsx
src/styles/components/_code-block.scss
src/styles/components/_component-card.scss
src/styles/components/_component-grid.scss
src/styles/components/_definition.scss
src/styles/components/_details-page.scss
src/styles/components/_detailsBanner.scss
src/styles/components/_footer.scss
src/styles/components/_header.scss
src/styles/components/_home.scss
src/styles/components/_related-components.scss
src/styles/components/_specification-block.scss
src/styles/components/_usage-guidelines.scss
src/styles/elements/_elements.scss
src/styles/globals.scss
src/styles/tools/_functions.scss
src/styles/tools/_mixins.scss

Refactoring was done in the SCSS files to ensure that media queries were not far removed from the elements they target. I divided up several long queries into shorter ones, and nested them within the selectors. 
Designs: [Figma file](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A270&t=Z1mZXyHn90lItsyX-0)
See Story: [FSA22V2-297](https://sparkbox.atlassian.net/browse/FSA22V2-297)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password …

style: refactor SCSS queries

---

src/components/RelatedComponents.jsx

Rename Component Inventory to Related Components
See Story: [FSA22V2-302](https://sparkbox.atlassian.net/browse/FSA22V2-302)
5. Run `npm run lint` to confirm no errors.
6. Run `npm run test` to confirm all tests pass.
7. In terminal: `npm run dev`.
8. Check …

FSA22V2-302 Refactor: rename component inventory

---

src/styles/components/_home.scss

FSA22V2-294
- improve code within breakpoint-large-screen-860 to prevent h1 from stacking at that breakpoint.
Designs: [Designs](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=244%3A2183&t=A0sL00y3exNBMMfW-0)
See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-294?atlOrigin=eyJpIjoiYTdlZTVmMmVlMDE5NDE3YWEwZTA3YzM1NGQ3YWNmYzciLCJwIjoiaiJ9)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and …

feat: eliminate h1 stacking at breakpoint

---

src/components/SpecificationBlock.jsx
src/pages/[id].page.jsx
src/styles/components/_specification-block.scss
src/styles/settings/_breakpoints.scss
src/utils/masonryDetails.js

FSA22V2-292
- add two column masonry layout to specifications grid.
Designs: [Designs](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A663&t=BPQNtzeTJP9dm997-0)
See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-ISSUE)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created `.env.local` file. That should establish your connection to …

feat: add two column masonry layout

---

src/components/DetailsBanner.jsx
src/components/DetailsBanner.test.jsx
src/components/Header.jsx
src/components/Header.test.jsx
src/components/Layout.jsx
src/components/Layout.test.jsx
src/pages/index.page.jsx
src/styles/components/_details-page.scss
src/styles/components/_detailsBanner.scss
src/styles/components/_home.scss

Some refactoring had to be done in order to limit the height of the interior page banners. With taller images, that banner was very long, so a new max-height was put on the images, as well as creating a new grid for multiple illustrations of the components in the banner section. Lastly, the header component needed to be located in a different place in order to inherit the background image of the details banner.
Designs: 
With Jelly's input, the background of the image grid has changed to a solid color in order to prevent the component illustrations from competing with the background image. She also requested 5rem from the top of the homepage link to the top of the viewport. Both of these changes are not found in the screenshot above, but can be seen on the site. 
See Story: …

FSA22V2-304: Refactor: Adjust the details page banner

---

src/styles/components/_code-block.scss
src/styles/components/_component-card.scss
src/styles/components/_definition.scss
src/styles/components/_detailsBanner.scss
src/styles/components/_footer.scss
src/styles/components/_home.scss
src/styles/components/_related-components.scss
src/styles/components/_specification-block.scss
src/styles/components/_usage-guidelines.scss
src/styles/layout/_component-grid.scss
src/styles/settings/_font_map.scss

-Adjust font-sizes to a "base 4" set of sizes. This should allow for easier math when calculating rems. 
-Add a 'mobile-heading' variable for the font_map. 
_After checking with the designer:_
-There should be no more 18px values (they've all been updated to 20px/"sm")
-There should be no more 25px values (they've all been updated to 24px/"mobile-heading")
Our font sizes have been refactored according to this new font-map: 
```
$font-sizes: (
"xs": 1rem, // 16px
"sm": 1.25rem, // 20px
"mobile-heading": 1.5rem, // 24px 
"md": 2rem, // 32px
"lg": 2.5rem, // 40px
"xl": 3.25rem, // 52px
);
```
See Story: [FSA22V2-313](https://sparkbox.atlassian.net/browse/FSA22V2-313)
3. …

FSA22V2-313: Refactor: Font Size Audit

---

src/styles/components/_specification-block.scss
src/utils/masonryDetails.js

- create mock masonry layout for specification blocks that will work on web browsers that do not support grid-template-rows masonry setting.
FSA22V2-319
See Story: [FSA22V2-ISSUE](https://sparkbox.atlassian.net/browse/FSA22V2-ISSUE)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created `.env.local` file. That should establish your connection to our Airtable …

feat: add masonry layout for specification blocks

---

src/styles/components/_code-block.scss
src/styles/components/_component-card.scss
src/styles/components/_definition.scss
src/styles/components/_detailsBanner.scss
src/styles/components/_footer.scss
src/styles/components/_header.scss
src/styles/components/_home.scss
src/styles/components/_related-components.scss
src/styles/components/_specification-block.scss
src/styles/components/_usage-guidelines.scss
src/styles/globals.scss
src/styles/settings/_line_height_map.scss

-Add a line-height map to keep all line-height values in one place. 
-Remove units on line-height properties and recalculate appropriately with current font sizes, instead of base font-size.
**Note:** when we initially built the component cards, the line-height in Figma was 75px. That has since been changed, but we never updated it. When I put in the more accurate 28px for the card headers, it no longer matched the designs. That's why I had to add the height and flex properties.
See Story: [FSA22V2-316](https://sparkbox.atlassian.net/browse/FSA22V2-316)
4. Copy the …

FSA22V2-316: Refactor: Line-height units & calculations

---

src/components/Footer.jsx
src/styles/components/_footer.scss

- Reduces the size of footer contents: icons are 30% smaller, and text is decreased from 20px to 16px.
- Margins/padding reduced to fit the proportions of the original design.
- Simplifies CSS slightly by removing redundant values
Designs: Intentionally strays from [the Figma design](https://www.figma.com/file/UjMQEwUvAsnFAMhYNdUiVT/Apprenticeship-Capstone?node-id=84%3A270&t=siw0s6v4jF6pxW5R-0). The 16px font and smaller icons were approved by Merani.
See Story: [FSA22V2-286](https://sparkbox.atlassian.net/browse/FSA22V2-286)
4. Copy the `.env.example` file, making sure …

Styling: decrease size of footer contents

---

src/styles/components/_specification-block.scss
src/styles/generics/_root.scss
src/styles/settings/_colors.scss

In the specification blocks, the code tags were originally designed to be blue. We have changed that so they are not misunderstood to be links. Additionally, the font was changed to the default monospace `code` font to ensure these elements are clearly  distinguished from the rest of the content.
BEFORE: 
AFTER:
See Story: [FSA22V2-312](https://sparkbox.atlassian.net/browse/FSA22V2-312)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. …

FSA22V2-312: Refactor: Code Elements are no longer blue

---

src/components/ErrorContent.jsx
src/pages/404.page.jsx
src/styles/components/_404.scss
src/styles/components/_footer.scss
src/styles/globals.scss
src/styles/layout/_layout.scss

Give the 404 page similar styles to the rest of the project. After speaking with Kaitlyn and double checking the copy, this included adding a few contextual sentences, a homepage link, and our image of Max! 
See Story: [FSA22V2-326](https://sparkbox.atlassian.net/browse/FSA22V2-326)
4. Copy the `.env.example` file, making sure it's in the root of your project, and rename it `.env.local`. Search for "Accessible Components" in 1Password to find the API Key and Base ID. Add both of those secrets to your newly created `.env.local` file. That should establish your connection …

FSA22V2-326: Feat: Add 404 page styles

---

src/styles/components/_component-link.scss
src/styles/components/_details-banner.scss
src/styles/components/_home.scss
src/styles/elements/_elements.scss
src/styles/globals.scss
src/styles/layout/_component-grid.scss

Some minor style fixes were implemented to continue to refine and match the homepage designs. This PR includes: 
- Refactoring the grid columns & rows to be a consistent size (using `fr` and `repeat`)
- Add an additional 2-column grid layout to accommodate more "medium" sized screens
- Use `:focus:not(:focus-visible)` on the component cards to prevent them from rotating when you click on them, but not when you tab to them
- Because the 1.4 value seemed too large, use `calc` to adjust the line-heights of all `h1` headings. 
See Story: [FSA22V2-321](https://sparkbox.atlassian.net/browse/FSA22V2-321)
3. Run `npm install` to make sure you have all proper dependencies. (this …

FSA22V2-321: Fix style problems on home page

---

.github/pull_request_template.md
.github/workflows/main.yml

This updates the GitHub Action that checks commit message formatting to look for the new Jira board's card number format: "AC-" instead of "FSA22V2-"
See Story: [Jira card](https://sparkbox.atlassian.net/browse/AC-1)

chore: check for the new board's card numbers

---

src/pages/[id].page.jsx
src/utils/airtable.js

For some reason, setting the `base` variable was throwing an error on the home page, but not the component pages. Moving the variable declaration into the `getComponentDetails` and `getHomePageInfo` seems to resolve the issue.
Changing the functions to named exports instead of having one name and one default was done for consistency more than anything.
See Story: [Jira card](https://sparkbox.atlassian.net/browse/AC-19)
7. In terminal: `npm run dev`.
8. Check [localhost:3000](http://localhost:3000/) to make sure you don't get an error about Airtable needing API keys.
9. Navigate to the other components and confirm the same
10. Go to the deploy preview and confirm that no …

fix: api key access issue

---

src/pages/index.page.jsx

This fixes an issue with expiring images hosted in Airtable that break the image references over time.
See Story: [Jira card](https://sparkbox.atlassian.net/browse/AC-20)
3. Run `npm run dev` and navigate to http://localhost:3000
4. You may see an error about the Airtable API Key, which is addressed in #165. You can dismiss the error without causing trouble
5. Confirm that the default and hover images load correctly and toggle as expected on hover

fix: use local image files instead of Airtable images

---

src/components/ComponentCard.jsx
src/pages/index.page.jsx

AC-17
This changes the names of the `ComponentCard` props from `imageOpen` and `imageClosed` to `defaultImage` and `hoverImage` to more accurately describe their purpose and to match the Airtable values. 
See Story: [Jira card](https://sparkbox.atlassian.net/browse/AC-17)
3. Run `npm run lint` to confirm no errors.
4. Run `npm run test` to confirm all tests pass.
7. In terminal: `npm run dev`.
8. Check [localhost:3000](http://localhost:3000/) and make sure that the images still show up as expected.

refactor: change image prop names to defaultImage and hoverImage

---

.eslintrc.json
.github/dependabot.yml
.stylelintrc.json
cypress/e2e/smoke.cy.js
jest.config.js
package-lock.json
package.json
src/components/RichText.test.jsx
src/pages/[id].page.jsx
src/pages/_document.page.jsx

This adds `eslint-config-prettier` and `stylelint-config-prettier` to avoid conflicting Prettier and ESLint/Stylelint rules. It also runs Prettier against the whole code-base to fix up any existing issues.
Update: about 1 day after creating this PR, `stylelint` released version 15, which deprecates all the rules that `stylelint-config-prettier` disables, so it turns out we don't need that 😄 
See Story: [Jira card](https://sparkbox.atlassian.net/browse/AC-21)
3. Run `npm ci`
4. Mess up some syntax (change indentation/whitespace, delete semicolons, etc.)
5. Run Prettier against any changed files and confirm that it formats the files without introducing linting errors

fix: prettier conflicts with linting rules

---

src/pages/[id].page.jsx
src/pages/index.page.jsx
src/utils/airtable.js

This adds support for controlling whether components are published in Airtable. In development environments, drafts are shown, but production environments will filter drafted components out.
This required changing `fallback` to false in `getStaticProps`, since we should want components to 404 if they haven't been published. We are also dynamically generating the paths instead of hard-coding known components, giving us more flexibility for adding components.
In Airtable, there is a new column called "Published" that is boolean and drives this behavior.
See Story: [Jira card](https://sparkbox.atlassian.net/browse/AC-9)
3. In Airtable, make sure at least one of the …

feat: support drafted/published components

---

src/pages/_document.page.jsx

Adds Google Tag Manager so the Outreach team can collect Analytics data.
See Story: [SC-1719](https://sparkbox.atlassian.net/browse/SC-1719)
1. Make sure all PR Checks have passed - the commit check isn't going to pass because this isn't an `AC-` prefixed card, it's a `SC-` prefixed card.
2. Open the [Netlify Deploy Preview](https://deploy-preview-213--accessible-components-cheatsheet.netlify.app/)
3. Inspect the code and confirm that you see Google Tag Manager scripts in the head, and a noscript in the body, that match the code snippets Kaitlyn gave us in the card
[SC-1719]: https://sparkbox.atlassian.net/browse/SC-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add Google Tag Manager

---

.github/workflows/main.yml

Since this project is not under active development tracking tickets, we can remove the ticket number check from CI.
Make sure all PR Checks have passed

chore: remove ticket number check from CI
